[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Erhöht die Baudrate für den seriellen Monitor
monitor_speed = 115200

; WICHTIG: Das "Huge APP" Schema wird benötigt, da Bluetooth Classic + BLE 
; den Standard-Speicherplatz (1.2MB) überschreiten.
board_build.partitions = huge_app.csv

; Die Bluetooth-Bibliotheken sind im ESP32-Core enthalten, 
; daher sind hier meist keine externen lib_deps nötig.
upload_port = COM3
monitor_port = COM3